# Generated by Django 6.0.5 on 2026-06-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eleves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=10)),
                ('date_naissance', models.DateField()),
                ('niveau', models.CharField(max_length=50)),
                ('num_educmaster', models.CharField(max_length=20, unique=True)),
                ('statut', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
            ],
        ),
    ]
