# Generated by Django 6.0.5 on 2026-06-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=10)),
                ('date_naissance', models.DateField()),
                ('identifiant', models.CharField(max_length=50)),
                ('poste', models.CharField(choices=[('Professeur', 'Professeur'), ('Directeur', 'Directeur'), ('Assistant', 'Assistant'), ('Administratif', 'Administratif'), ('Autre', 'Autre')], default='Professeur', max_length=50)),
                ('num_educmaster', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], default='Actif', max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('classes', models.JSONField(null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
