# Generated by Django 6.0.5 on 2026-06-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploies',
            name='nombre_heure',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='emploies',
            name='matiere',
            field=models.TextField(max_length=150, null=True, unique=True),
        ),
    ]
