# Generated by Django 6.0.5 on 2026-06-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploie', '0002_emploies_nombre_heure_alter_emploies_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploies',
            name='heure_debut',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='emploies',
            name='heure_fin',
            field=models.CharField(),
        ),
    ]
