# Generated by Django 6.0.5 on 2026-06-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploie', '0003_alter_emploies_heure_debut_alter_emploies_heure_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emploies',
            name='matiere',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
