# Generated by Django 6.0.5 on 2026-07-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matiere', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matieres',
            name='coefficient',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matieres',
            name='nom',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
