# Generated by Django 6.0.5 on 2026-06-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleve', models.CharField(max_length=100)),
                ('matiere', models.CharField(max_length=150)),
                ('niveau', models.CharField(max_length=50)),
                ('int1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('int2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('int3', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('int4', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('moy_int', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('devoir', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('compo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('moyen_trim', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('trimestre', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
